"use server";

/**
 * Cross-Model Verification System
 * Uses a second AI model to verify/audit content generated by Gemini
 * 
 * Specification: @commands/cross-model-verification.md
 * 
 * Currently supports:
 * - Anthropic Claude (via @anthropic-ai/sdk)
 * - OpenAI GPT-4 (via openai) - DEFAULT
 * - Gemini Pro (uses existing GEMINI_API_KEY)
 * 
 * To use: Add the appropriate API key to .env.local
 */

// Example implementation for Anthropic Claude
// Install: npm install @anthropic-ai/sdk

export interface VerificationResult {
  verified: boolean;
  score: number; // 0-10
  feedback: string;
  issues: string[];
  suggestions: string[];
}

export type VerifierModel = "claude" | "openai" | "gemini-pro";

/**
 * Verify content using Claude (Anthropic)
 */
export async function verifyWithClaude(
  originalContent: string,
  context?: string
): Promise<VerificationResult> {
  // Check if API key is available
  if (!process.env.ANTHROPIC_API_KEY) {
    throw new Error("ANTHROPIC_API_KEY not set. Add it to .env.local");
  }

  // Dynamic import to avoid errors if package not installed
  try {
    // @ts-expect-error - @anthropic-ai/sdk is an optional dependency
    const { Anthropic } = await import("@anthropic-ai/sdk");
    const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });

    const systemPrompt = `You are a Quality Assurance Auditor for AI-generated content. Your task is to verify the accuracy, completeness, and quality of content generated by another AI model (Gemini).

Review the content for:
1. **Factual Accuracy:** Are there any hallucinations, incorrect facts, or unsupported claims?
2. **Logical Consistency:** Does the reasoning flow logically? Are there contradictions?
3. **Completeness:** Is important information missing?
4. **Clarity:** Is the content clear and well-structured?
5. **Bias or Errors:** Are there any biases, logical fallacies, or errors?

Provide:
- A verification score (0-10)
- Specific issues found (if any)
- Suggestions for improvement
- Overall verdict (verified/needs revision)`;

    const userPrompt = `${context ? `Context: ${context}\n\n` : ""}Content to verify:\n\n${originalContent}`;

    const message = await anthropic.messages.create({
      model: "claude-3-5-sonnet-20241022", // or claude-3-opus-20240229 for stronger reasoning
      max_tokens: 2000,
      system: systemPrompt,
      messages: [
        {
          role: "user",
          content: userPrompt,
        },
      ],
    });

    const response = message.content[0];
    if (response.type !== "text") {
      throw new Error("Unexpected response type from Claude");
    }

    // Parse the response (you might want to use structured output or JSON mode)
    const feedback = response.text;
    
    // Simple parsing - you can improve this with structured output
    const scoreMatch = feedback.match(/score[:\s]+(\d+(?:\.\d+)?)/i);
    const score = scoreMatch ? parseFloat(scoreMatch[1]) : 5;

    return {
      verified: score >= 7,
      score: Math.min(10, Math.max(0, score)),
      feedback,
      issues: extractIssues(feedback),
      suggestions: extractSuggestions(feedback),
    };
  } catch (error) {
    if (error instanceof Error && error.message.includes("Cannot find module")) {
      throw new Error(
        "@anthropic-ai/sdk not installed. Run: npm install @anthropic-ai/sdk"
      );
    }
    throw error;
  }
}

/**
 * Verify content using OpenAI GPT-4
 */
export async function verifyWithOpenAI(
  originalContent: string,
  context?: string
): Promise<VerificationResult> {
  if (!process.env.OPENAI_API_KEY) {
    throw new Error("OPENAI_API_KEY not set. Add it to .env.local");
  }

  try {
    // @ts-expect-error - openai is an optional dependency
    const OpenAI = (await import("openai")).default;
    const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

    const systemPrompt = `You are a Quality Assurance Auditor for AI-generated content (Cross-Model Verification from cross-model-verification.md).

Review the content for:
1. **Factual Accuracy:** Identify hallucinations, incorrect facts, or unsupported claims.
2. **Logical Consistency:** Check if reasoning flows logically and identify contradictions.
3. **Completeness:** Determine if important information is missing.
4. **Clarity & Structure:** Evaluate if content is clear and well-organized.
5. **Bias & Errors:** Detect biases, logical fallacies, or systematic errors.

Provide:
- A verification score (0-10, where 7+ = verified, <7 = needs revision)
- Specific issues found (if any)
- Suggestions for improvement
- Overall verdict (verified/needs revision)

Format your response with clear sections for Score, Issues, and Suggestions.`;

    const completion = await openai.chat.completions.create({
      model: "gpt-4-turbo-preview", // or gpt-4 for stronger reasoning
      messages: [
        { role: "system", content: systemPrompt },
        {
          role: "user",
          content: `${context ? `Context: ${context}\n\n` : ""}Content to verify:\n\n${originalContent}`,
        },
      ],
      temperature: 0.3,
    });

    const feedback = completion.choices[0]?.message?.content || "";
    const scoreMatch = feedback.match(/score[:\s]+(\d+(?:\.\d+)?)/i);
    const score = scoreMatch ? parseFloat(scoreMatch[1]) : 5;

    return {
      verified: score >= 7,
      score: Math.min(10, Math.max(0, score)),
      feedback,
      issues: extractIssues(feedback),
      suggestions: extractSuggestions(feedback),
    };
  } catch (error) {
    if (error instanceof Error && error.message.includes("Cannot find module")) {
      throw new Error("openai not installed. Run: npm install openai");
    }
    throw error;
  }
}

/**
 * Verify using another Gemini model (no additional API key needed)
 */
export async function verifyWithGeminiPro(
  originalContent: string,
  context?: string
): Promise<VerificationResult> {
  if (!process.env.GEMINI_API_KEY) {
    throw new Error("GEMINI_API_KEY not set");
  }

  const { GoogleGenerativeAI } = await import("@google/generative-ai");
  const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

  const model = genAI.getGenerativeModel({
    model: "gemini-2.5-pro", // Use Pro to verify Flash output
  });

  const prompt = `You are a Quality Assurance Auditor. Review this AI-generated content for accuracy, completeness, and quality.

${context ? `Context: ${context}\n\n` : ""}Content to verify:\n\n${originalContent}

Provide a verification score (0-10), identify issues, and suggest improvements.`;

  const result = await model.generateContent(prompt);
  const response = result.response;
  const feedback = response.text();

  const scoreMatch = feedback.match(/score[:\s]+(\d+(?:\.\d+)?)/i);
  const score = scoreMatch ? parseFloat(scoreMatch[1]) : 5;

  return {
    verified: score >= 7,
    score: Math.min(10, Math.max(0, score)),
    feedback,
    issues: extractIssues(feedback),
    suggestions: extractSuggestions(feedback),
  };
}

/**
 * Unified verification function - automatically selects available verifier
 * Defaults to OpenAI if available, falls back to others
 */
export async function verifyContent(
  originalContent: string,
  verifier: VerifierModel = "openai",
  context?: string
): Promise<VerificationResult> {
  switch (verifier) {
    case "claude":
      return verifyWithClaude(originalContent, context);
    case "openai":
      return verifyWithOpenAI(originalContent, context);
    case "gemini-pro":
      return verifyWithGeminiPro(originalContent, context);
    default:
      throw new Error(`Unknown verifier: ${verifier}`);
  }
}

// Helper functions
function extractIssues(text: string): string[] {
  const issues: string[] = [];
  const issuePatterns = [
    /issues?[:\s]+(.*?)(?=\n\n|\n[A-Z]|$)/gis,
    /problems?[:\s]+(.*?)(?=\n\n|\n[A-Z]|$)/gis,
    /errors?[:\s]+(.*?)(?=\n\n|\n[A-Z]|$)/gis,
  ];

  for (const pattern of issuePatterns) {
    const matches = text.matchAll(pattern);
    for (const match of matches) {
      if (match[1]) {
        issues.push(match[1].trim());
      }
    }
  }

  return issues.length > 0 ? issues : ["No specific issues identified"];
}

function extractSuggestions(text: string): string[] {
  const suggestions: string[] = [];
  const suggestionPatterns = [
    /suggestions?[:\s]+(.*?)(?=\n\n|\n[A-Z]|$)/gis,
    /recommendations?[:\s]+(.*?)(?=\n\n|\n[A-Z]|$)/gis,
    /improvements?[:\s]+(.*?)(?=\n\n|\n[A-Z]|$)/gis,
  ];

  for (const pattern of suggestionPatterns) {
    const matches = text.matchAll(pattern);
    for (const match of matches) {
      if (match[1]) {
        suggestions.push(match[1].trim());
      }
    }
  }

  return suggestions.length > 0
    ? suggestions
    : ["No specific suggestions provided"];
}
